"""Initial migration

Revision ID: a190e15e234f
Revises: 
Create Date: 2025-03-16 14:44:16.864209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a190e15e234f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=8), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character'),
    sa.UniqueConstraint('frame_number')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('primitive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(length=8), nullable=False),
    sa.Column('meaning', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element')
    )
    op.create_table('character_keywords',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'keyword_id')
    )
    op.create_table('character_primitives',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('primitive_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['primitive_id'], ['primitive.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'primitive_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_primitives')
    op.drop_table('character_keywords')
    op.drop_table('primitive')
    op.drop_table('keyword')
    op.drop_table('character')
    # ### end Alembic commands ###
