// Example library with 15 entries demonstrating all three entry types
// (primitive, dual, character) with interconnected component relationships.

const exampleEntries = [
  // ── Primitives ──────────────────────────────────────────────────────────────
  {
    id: 'ex-mouth',
    character: '口',
    keyword: '',
    primitiveKeywords: ['Mouth'],
    heisigNumber: null,
    bookNumber: null,
    lessonNumber: null,
    strokeCount: 3,
    story: '',
    componentIds: [],
    isMastered: false,
  },
  {
    id: 'ex-tree',
    character: '木',
    keyword: '',
    primitiveKeywords: ['Tree'],
    heisigNumber: null,
    bookNumber: null,
    lessonNumber: null,
    strokeCount: 4,
    story: '',
    componentIds: [],
    isMastered: false,
  },
  {
    id: 'ex-field',
    character: '田',
    keyword: '',
    primitiveKeywords: ['Rice field'],
    heisigNumber: null,
    bookNumber: null,
    lessonNumber: null,
    strokeCount: 5,
    story: '',
    componentIds: [],
    isMastered: false,
  },
  {
    id: 'ex-drop',
    character: '丶',
    keyword: '',
    primitiveKeywords: ['Drop'],
    heisigNumber: null,
    bookNumber: null,
    lessonNumber: null,
    strokeCount: 1,
    story: '',
    componentIds: [],
    isMastered: false,
  },

  // ── Dual entries (keyword + primitive keywords) ─────────────────────────────
  {
    id: 'ex-sun',
    character: '日',
    keyword: 'Day',
    primitiveKeywords: ['Sun'],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 1,
    strokeCount: 4,
    story: 'A window you look through to see the day outside — a little box with a line across it, like the horizon dividing the view.',
    componentIds: [],
    isMastered: true,
  },
  {
    id: 'ex-moon',
    character: '月',
    keyword: 'Month',
    primitiveKeywords: ['Moon', 'Flesh'],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 1,
    strokeCount: 4,
    story: 'A crescent moon marks the passing of each month. The two inner strokes are the dark craters you can see on its face.',
    componentIds: [],
    isMastered: true,
  },
  {
    id: 'ex-person',
    character: '人',
    keyword: 'Person',
    primitiveKeywords: ['Person', 'Legs'],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 1,
    strokeCount: 2,
    story: 'Two strokes leaning on each other — a person needs support to stand, just like these two lines need each other to stay upright.',
    componentIds: [],
    isMastered: false,
  },

  // ── Characters (composed from the above) ────────────────────────────────────
  {
    id: 'ex-bright',
    character: '明',
    keyword: 'Bright',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 1,
    strokeCount: 8,
    story: 'The [[Sun]] and the [[Moon]] standing side by side — together they make everything bright, as if day and night are shining at once.',
    componentIds: ['ex-sun', 'ex-moon'],
    isMastered: true,
  },
  {
    id: 'ex-rest',
    character: '休',
    keyword: 'Rest',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 1,
    strokeCount: 6,
    story: 'A [[Person]] leaning against a [[Tree]], taking a well-deserved rest in the shade after a long walk.',
    componentIds: ['ex-person', 'ex-tree'],
    isMastered: false,
  },
  {
    id: 'ex-grove',
    character: '林',
    keyword: 'Grove',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 2,
    strokeCount: 8,
    story: 'Two [[Tree|trees]] growing side by side — not yet a forest, but a pleasant little grove where you might have a picnic.',
    componentIds: ['ex-tree'],
    isMastered: false,
  },
  {
    id: 'ex-think',
    character: '思',
    keyword: 'Think',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 2,
    strokeCount: 9,
    story: 'A [[Rice field]] sitting on top of a heart. To think is to cultivate the fields of your mind — planting ideas in rows like rice seedlings.',
    componentIds: ['ex-field'],
    isMastered: false,
  },
  {
    id: 'ex-early',
    character: '早',
    keyword: 'Early',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 2,
    strokeCount: 6,
    story: 'The [[Sun]] has barely risen — just a [[Drop]] of light above the horizon. That\'s how early it is.',
    componentIds: ['ex-sun', 'ex-drop'],
    isMastered: false,
  },
  {
    id: 'ex-fat',
    character: '太',
    keyword: 'Fat',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 1,
    strokeCount: 4,
    story: 'A [[Person]] with an extra [[Drop]] — one drop too many at dinner, and now they\'re fat!',
    componentIds: ['ex-person', 'ex-drop'],
    isMastered: false,
  },
  {
    id: 'ex-woods',
    character: '森',
    keyword: 'Forest',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 3,
    strokeCount: 12,
    story: 'A [[Tree]] on top of a grove — three trees together make a full forest. You can hear the wind rustling through all those leaves.',
    componentIds: ['ex-tree'],
    isMastered: false,
  },
  {
    id: 'ex-stomach',
    character: '胃',
    keyword: 'Stomach',
    primitiveKeywords: [],
    heisigNumber: null,
    bookNumber: 1,
    lessonNumber: 3,
    strokeCount: 9,
    story: 'A [[Rice field]] sitting on top of [[Moon|flesh]]. The stomach is the field inside your body where food gets broken down.',
    componentIds: ['ex-field', 'ex-moon'],
    isMastered: false,
  },
]

export default exampleEntries
